name: redstone_web_socket
version: 0.0.1
description: A Websocket plugin for Redstone.dart
author: Luiz Mineo <luiz.mineo@gmail.com>
homepage: http://redstonedart.org
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  redstone: ">=0.5.13 <0.6.0"
  shelf_web_socket: ">=0.0.1 < 0.1.0"
  di: ">=2.0.1 <3.0.0"
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
