name: redstone_web_socket
version: 0.2.0
description: A web socket plugin for Redstone.dart
author: Luiz Mineo <luiz.mineo@gmail.com>
homepage: http://redstonedart.org

environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

dependencies:
  redstone:
    git:
      url: https://github.com/dartsome/redstone.git
      ref: cf6fff976135f28256cf98db560774a05d08634d
  shelf_web_socket: ^0.2.2+2

dev_dependencies:
  test: ^1.2.0

#dependency_overrides:
#  redstone:
#    path: ../redstone_2
